---
# tasks file for odoo-backup

- name: Create backup directory
  file:
    path: "{{ backup_dir }}"
    state: directory
    mode: '0755'

- name: Dump Odoo database {{ odoo_db_name }}
  postgresql_db:
    name: "{{ odoo_db_name }}"
    login_user: "{{ odoo_db_user }}"
    login_password: "{{ odoo_db_password }}"
    login_host: "{{ odoo_db_host }}"
    login_port: "{{ odoo_db_port }}"
    state: dump
    target: "{{ backup_file }}"

