---
# defaults file for nginx-odoo

odoo_aliases: []
odoo_forwards: []
odoo_version: 18
odoo_list_db: false
odoo_backend: 127.0.0.1
odoo_backend_port: 8069
odoo_backend_port_websocket: 8072
odoo_workers: 2
odoo_client_max_body_size: 16M
