# Docker compose file for {{ deployment_name }}

volumes:
  {{ odoo_volume_definitions | to_nice_yaml(indent=4) | trim }}
  odoo-host:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "{{ odoo_host_dir }}"
services:
  odoo-update:
    image: "{{ odoo_image }}"
    volumes:
      {{ odoo_volumes | to_nice_yaml(indent=6) | trim }}
    command: ['update']
  odoo:
    image: "{{ odoo_image }}"
    restart: always
    volumes:
      {{ odoo_volumes | to_nice_yaml(indent=6) | trim }}
    ports:
      - "{{ odoo_backend_port }}:8069"
      - "{{ odoo_backend_port_websocket }}:8072"
    deploy:
      restart_policy:
        condition: any
        delay: 5s
    depends_on:
      odoo-update:
        condition: service_completed_successfully
  odoo-cron:
    image: "{{ odoo_image }}"
    restart: always
    environment:
      ODOO_CONFIG_NAME: "odoo-cron.conf"
    volumes:
      {{ odoo_volumes | to_nice_yaml(indent=6) | trim }}
    deploy:
      restart_policy:
        condition: any
        delay: 10s
    depends_on:
      odoo-update:
        condition: service_completed_successfully