[options]
without_demo = True
admin_passwd = {{ odoo_admin_password | mandatory }}
{% if not odoo_list_db is defined or not odoo_list_db %}
list_db = False
{% endif %}
{% if odoo_db_name is defined %}
db_name = {{ odoo_db_name }}
{% endif %}
{% if odoo_db_filter is defined %}
db_filter = {{ odoo_db_filter }}
{% endif %}
{% if odoo_db_prefix is defined %}
db_prefix = {{ odoo_db_prefix }}
{% endif %}
{% if odoo_db_user is defined %}
db_user = {{ odoo_db_user }}
{% endif %}
{% if odoo_db_password is defined %}
db_password = {{ odoo_db_password }}
{% endif %}
{% if odoo_db_host is defined %}
db_host = {{ odoo_db_host }}
{% endif %}
log_handler = [':INFO']
log_level = info
proxy_mode = True
{% if odoo_db_template is defined %}
db_template = {{ odoo_db_template }}
{% endif %}
data_dir = {{ odoo_data_dir }}
# cron specific
max_cron_threads = {{ odoo_cron_threads }}
{% if odoo_queue is defined and odoo_queue %}
server_wide_modules = web,queue_job
{% endif %}
workers = -1
xmlrpc = True
xmlrpc_port = 8069
xmlrpcs = False
# backround task specific
limit_time_real_cron = 0
limit_time_real = 0
limit_memory_soft = 0
limit_memory_hard = 0
# queue specific
{% if odoo_queue_root is defined %}
[queue_job]
channels = root:{{ odoo_queue_root }}
{% endif %}