[options]
without_demo = True
admin_passwd = {{ odoo_admin_password | mandatory }}
{% if not odoo_list_db is defined or not odoo_list_db %}
list_db = False
{% endif %}
{% if odoo_db_name is defined %}
db_name = {{ odoo_db_name }}
{% endif %}
{% if odoo_db_filter is defined %}
db_filter = {{ odoo_db_filter }}
{% endif %}
{% if odoo_db_prefix is defined %}
db_prefix = {{ odoo_db_prefix }}
{% endif %}
{% if odoo_db_user is defined %}
db_user = {{ odoo_db_user }}
{% endif %}
{% if odoo_db_password is defined %}
db_password = {{ odoo_db_password }}
{% endif %}
{% if odoo_db_host is defined %}
db_host = {{ odoo_db_host }}
{% endif %}
{% if odoo_db_maxconn is defined %}
db_maxconn = {{ odoo_db_maxconn }}
{% endif %}
log_handler = [':INFO']
log_level = info
proxy_mode = True
{% if odoo_db_template is defined %}
db_template = {{ odoo_db_template }}
{% endif %}
data_dir = {{ odoo_data_dir }}
# worker config
gevent_port = 8072
{% if odoo_workers > 0 %}
max_cron_threads = 0
workers = {{ odoo_workers }}
{% else %}
max_cron_threads = {{ odoo_cron_threads }}
workers = 0
{% if odoo_queue is defined and odoo_queue %}
server_wide_modules = web,queue_job
{% endif %}
{% endif %}
xmlrpc = True
xmlrpc_port = 8069
xmlrpcs = False
# queue config
{% if odoo_queue_root is defined and not odoo_workers %}
[queue_job]
channels = root:{{ odoo_queue_root }}
{% endif %}