#!/bin/sh
for DEPLOYMENT in "$@"
do
    kubectl get deployment $DEPLOYMENT
    if [ $? -eq 0 ]; then
        set -e
        echo "Scale to 0 for deployment $DEPLOYMENT"
        kubectl scale deployment $DEPLOYMENT --replicas=0
        kubectl rollout status deployment/$DEPLOYMENT
        set +e
    fi
done
exit 0