---
# tasks file for odoo-deployment

- name: Create volume
  docker_volume:
    name: "{{ deployment_name }}"

- name: Ensure volume access
  file:
    path: "{{ odoo_volume }}"
    state: directory
    owner: "{{ odoo_chown }}"
    group: "{{ odoo_chown }}"

- name: Pre-Create config dir
  ansible.builtin.file:
    path: "{{ odoo_volume_etc }}"
    state: directory
    owner: "{{ odoo_chown }}"
    group: "{{ odoo_chown }}"

- name: Copy odoo config
  template:
    src: "odoo.conf"
    dest: "{{ odoo_volume_etc }}/odoo.conf"
    owner: "{{ odoo_chown }}"
    group: "{{ odoo_chown }}"

- name: Copy odoo-cron config
  template:
    src: "odoo-cron.conf"
    dest: "{{ odoo_volume_etc }}/odoo-cron.conf"
    owner: "{{ odoo_chown }}"
    group: "{{ odoo_chown }}"

- name: Pre-Create filestore
  file:
    path: "{{ odoo_volume_filestore }}"
    state: directory
    owner: "{{ odoo_chown }}"
    group: "{{ odoo_chown }}"

- name: Pre-Create session dir
  file:
    path: "{{ odoo_volume_sessions }}"
    state: directory
    owner: "{{ odoo_chown }}"
    group: "{{ odoo_chown }}"

- name: Pre-Create logs dir
  file:
    path: "{{ odoo_volume_logs }}"
    state: directory
    owner: "{{ odoo_chown }}"
    group: "{{ odoo_chown }}"

- name: Check if filestore is empty
  find:
    path: "{{ odoo_volume_filestore }}"
    file_type: any
    pattern: '*'
    depth: 1
  register: filestore_dirs

- name: Restore filestore
  synchronize:
    src: "{{ odoo_filestore_backup }}/"
    dest: "{{ odoo_volume_filestore }}/"
    rsync_opts:
      - "--chown={{ odoo_chown }}:{{ odoo_chown }}"
  when: "filestore_dirs.matched == 0 and odoo_filestore_backup is defined"

- set_fact:
    odoo_volume_definitions: "{{ {deployment_name: {'external': True}} }}"

- name: Login to docker registry
  docker_login:
    registry_url: "{{ docker_registry }}"
    username: "{{ docker_user }}"
    password: "{{ docker_password }}"
    state: present
  when: docker_registry is defined and docker_registry

- name: Ensure deployment dir
  file:
    path: "{{ odoo_docker_compose_dir }}"
    state: directory

- name: Copy docker-compose.yml
  template:
    src: "docker-compose.yml"
    dest: "{{ odoo_docker_compose_dir }}/docker-compose.yml"